### ISSUE TITLE
Link to ColBERT PRF source

### ISSUE THREAD

**Issue by cmacdonald** [jihyukkim-nlp/CollectiveKD#1]
Hi all,

Thanks for using ColBERT PRF - as you have copied code from pyterrier_colbert, I think you could link to that repo from here as well?

**Comment by jihyukkim-nlp** [comment]
Dear Craig Macdonald,

Sorry, I accidentally forgot to link the code. 
I added the link.
Thank you for sharing awesome work and codes!

Best regards,
Jihyuk Kim

**Comment by cmacdonald** [comment]
Thanks Jihyuk!
